---
title: "Data Plus Simple Visualizations"
author: "Andrew Padgett"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(dplyr)
library(ggplot2)
library(tidyverse)     # for data cleaning and plotting
library(googlesheets4) # for reading googlesheet data
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(palmerpenguins)# for Palmer penguin data
library(maps)          # for map data       
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
#library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
library(transformr)    # for "tweening" (gganimate)
library(shiny)         # for creating interactive apps
library(patchwork)     # for nicely combining ggplot2 graphs  
library(gt)            # for creating nice tables
library(rvest)         # for scraping data
library(robotstxt)     # for checking if you can scrape data
gs4_deauth()           # To not have to authorize each time you knit.
library(mapproj)
theme_set(theme_minimal())
library(ggmap)
library(plotly)
```



```{r}
mn_contrib <- read.csv("indivs_Minnesota18.csv")

zip_codes <- read.csv("zip_code_database.csv")

committees <- read.csv("fecinfo.csv")

candidates <- read.csv("candidates.csv")
```



```{r}
states <- map_data("state")
mn_state <- subset(states, region == "minnesota")
counties <- map_data("county")
mn_county <- filter(counties, region == "minnesota") %>%
  select(-region) %>%
  mutate(region = subregion)
```


```{r}
main <- mn_contrib %>%
  mutate(Zip = as.numeric(Zip)) %>%
  left_join(zip_codes,
            by = "Zip") %>%
  mutate(county1 = str_to_lower(county),
         county2 = str_remove(county1, pattern = " county"),
         county2 = str_remove(county2, pattern = "\\.")) %>%
  select(-acceptable_cities, 
         -unacceptable_cities, 
         -state, 
         -decommissioned, 
         -country, 
         -world_region, 
         -area_codes, 
         -timezone, 
         -type, 
         -Microfilm, 
         -OtherID, 
         -Type, 
         -Realcode, 
         -Street, 
         -Ultorg, 
         -Contribid, 
         -Cycle, 
         -Recipcode, 
         -Source, 
         -primary_city, 
         -county, 
         -county1) %>%
  mutate(county = county2) %>%
  select(-county2) %>%
  left_join(committees, by = "CmteId") %>%
  left_join(candidates, by =  c("cm_cand_id" = "cand_id")) %>%
  select(-Fectransid, 
         -Recipid, 
         -CmteId, 
         -cm_treasurer_name, 
         -cm_address_line_1, 
         -cm_address_line_2, 
         -cm_city, 
         -cm_state, 
         -cm_zip, 
         -cm_desig, 
         -cm_type, 
         -cm_freq, 
         -cm_interest, 
         -cm_cand_id, 
         -cand_election_year, 
         -cand_status, 
         -cand_cmte, 
         -cand_st1, 
         -cand_st2, 
         -cand_zip,
         -cand_state2)

main
```

```{r}
main%>%
  select(Amount,Occupation)%>%
  mutate(retired= Occupation=="RETIRED")
```

```{r}
main%>%
  select(Occupation)%>%
  distinct(Occupation)
```

```{r, fig.height = 12}
main%>%
  filter(Gender == c("F", "M"), .keep_all = TRUE) %>%
  group_by(county, Gender) %>%
  mutate(total_contribs = n()) %>%
  filter(total_contribs > 25) %>%
  summarize(mean_amt = mean(Amount)) %>%
  ggplot(aes(x = mean_amt, y = county)) +
  geom_col(aes(fill = Gender))
```

```{r}
(main %>%
  filter(Gender == c("M", "F")) %>%
  group_by(county, Gender) %>%
  mutate(total_contribs = n()) %>%
  filter(total_contribs > 25) %>%
  summarize(mean_amt = mean(Amount)) %>%
  ggplot() + 
  geom_map(map = mn_county, aes(map_id = county, fill = mean_amt)) +
  expand_limits(x = mn_county$long, y = mn_county$lat) + 
  scale_fill_gradient(low = "white", high = "black") + 
  theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
  ) + 
  facet_wrap(~Gender)) %>%
  ggplotly()
```

```{r, fig.width = 10}
main %>%
  filter(Amount > 1) %>%
  ggplot(aes(x = Amount)) + 
  geom_histogram(bins = 30) + 
  scale_x_log10(breaks = scales::log_breaks(n=10), labels = scales::comma) + 
  scale_y_log10(breaks = scales::log_breaks(n=10), labels = scales::comma) +
  annotation_logticks(sides = "bl")
```
